const nome = prompt('Digite seu nome:');
const nomeLetras = (nome.length);
const segundaLetra = (nome[1]);
const indiceLetra1 = (nome.indexOf('L'));
const indiceUltima = (nome.lastIndexOf('a'))
const ultimasLetras = (nome.slice(-3))
const nomeUperCase = (nome.toUpperCase());
const nomeLoweCase = (nome.toLowerCase());
const palavras = (nome.split(' '));

document.body.innerHTML += `O seu nome completo é: ${nome} <br />`;
document.body.innerHTML += `Seu nome possui: ${nomeLetras} letras <br />`;
document.body.innerHTML += `A segunda letra do seu nome é: ${segundaLetra} <br/>`;
document.body.innerHTML += `Qual o indice da letra L no seu nome?: ${indiceLetra1} <br />`;
document.body.innerHTML += `Qual o ultimo indice da letra a do seu nome?: ${indiceUltima} <br/>`;
document.body.innerHTML += `As tres ultimas letras do seu nome são: ${ultimasLetras} <br/>`;
document.body.innerHTML += `Seu nome em upercase: ${nomeUperCase} <br/>`;
document.body.innerHTML += `Seu nome em lowcase é: ${nomeLoweCase} <br/>`;
document.body.innerHTML += `As palavras do seu nome são: ${palavras} <br/>`